// <auto-generated />
namespace ShareMyBike.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class size : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(size));
        
        string IMigrationMetadata.Id
        {
            get { return "201310281216546_size"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
