// <auto-generated />
namespace ShareMyBike.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class bike : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bike));
        
        string IMigrationMetadata.Id
        {
            get { return "201310281214141_bike"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
